import type { Category, Product } from "@/lib/types";

export const SEED_CATEGORIES: Category[] = [
  { id: "seed-cat-frutales", name: "Frutales", slug: "frutales", sortOrder: 1 },
  {
    id: "seed-cat-tropicales",
    name: "Tropicales",
    slug: "tropicales",
    sortOrder: 2,
  },
  { id: "seed-cat-clasicos", name: "Clásicos", slug: "clasicos", sortOrder: 3 },
  {
    id: "seed-cat-especiales",
    name: "Especiales",
    slug: "especiales",
    sortOrder: 4,
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: "seed-polar-blue",
    name: "Polar Blue",
    slug: "polar-blue",
    description: "Vodka, curaçao blue, limón y azúcar.",
    priceCop: 18000,
    accentColor: "#2EA6E0",
    imageUrl: "/images/polar-cocktail-product-transparent.png",
    categorySlug: "clasicos",
    categoryName: "Clásicos",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "seed-mora-polar",
    name: "Mora Polar",
    slug: "mora-polar",
    description: "Vodka, mora, limón y un toque de soda.",
    priceCop: 18000,
    accentColor: "#7B2FB0",
    imageUrl: "/images/polar-cocktail-purple-transparent.png",
    categorySlug: "frutales",
    categoryName: "Frutales",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "seed-tropical-mix",
    name: "Tropical Mix",
    slug: "tropical-mix",
    description: "Ron, maracuyá, piña y coco.",
    priceCop: 18000,
    accentColor: "#E0A52E",
    imageUrl: "/images/polar-cocktail-golden-transparent.png",
    categorySlug: "tropicales",
    categoryName: "Tropicales",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "seed-fresa-colada",
    name: "Fresa Colada",
    slug: "fresa-colada",
    description: "Ron, fresa, coco y piña.",
    priceCop: 18000,
    accentColor: "#E0457A",
    imageUrl: "/images/polar-cocktail-red-transparent.png",
    categorySlug: "tropicales",
    categoryName: "Tropicales",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: "seed-mango-loco",
    name: "Mango Loco",
    slug: "mango-loco",
    description: "Vodka, mango, chile y limón.",
    priceCop: 18000,
    accentColor: "#E0612E",
    imageUrl: "/images/polar-cocktail-mango-transparent.png",
    categorySlug: "frutales",
    categoryName: "Frutales",
    sortOrder: 5,
    isActive: true,
  },
  {
    id: "seed-polar-oreo",
    name: "Polar Oreo",
    slug: "polar-oreo",
    description: "Vodka, crema de menta, oreo y leche condensada.",
    priceCop: 18000,
    accentColor: "#3FB58A",
    imageUrl: "/images/polar-cocktail-mint-cookie-transparent.png",
    categorySlug: "especiales",
    categoryName: "Especiales",
    sortOrder: 6,
    isActive: true,
  },
];
